### ISSUE TITLE
EXE won't open

### ISSUE THREAD

**Issue by punknerd54** [Gamergotten/Infinite-runtime-tagviewer#110]
I am unable to run the exe for IRTV. Every time I try, it says I need .Net. Even after downloading .Net, I still get the same message. I've even tried downloading different versions of .Net and kept getting the same message

**Comment by Gamergotten** [comment]
in the readme you can find the link to download dot net 6.0 
if that does not work, you would have to go to the official dot net download section and find the download that suits your machine (for example i think x86/x64 uses a different dot net download?)

**Comment by Z-15** [comment]
No traffic in 22 days, closing.
