### ISSUE TITLE
broken after update

### ISSUE THREAD

**Issue by toomuchcodehelp** [Gamergotten/Infinite-runtime-tagviewer#115]
constantly throws: cant locate Haloinfinite.exe

**Comment by split29** [comment]
mhmm, same is happening to me

**Comment by toomuchcodehelp** [comment]
343i's anticheat might be to blame

**Comment by split29** [comment]
does it still open 4 you??

**Comment by toomuchcodehelp** [comment]
opens fine on .net 5, could you be using a newer/older version?

**Comment by Gamergotten** [comment]
not currently working on the tool, but could you give more details on what is/isn't working
the other guys have made tons of changes that have made it potentially unstable as hell, which i'll have to look into sometime

are you playing on winstore/steam, operating system?, is both the game & tool up to date
i dont think we ever ran into any issues regarding which store you installed infinite off of, but who knows
and i dont think win 10/11 should work any differently in that regard

im pretty sure the tool is working for the other guys, so thats weird that its not working for you two

maybe you aren't launching with admin perms (if it still needs that) i dunno

**Comment by toomuchcodehelp** [comment]
Running as Admin on steam, Win10 (havent tried it on linux yet), the problem is that even after telling it where haloinfinite.exe is, it cant find it.

**Comment by toomuchcodehelp** [comment]
seems that the latest developer build works fine? I can confirm this by making chief invincible with a poke. I won't close until i can verify that everything is fine.

**Comment by Z-15** [comment]
No comment in 6 days, so I'm closing. Original poster seems to of fixed the issue. I also tested the latest build and all tags seem to be loading properly.

**Comment by toomuchcodehelp** [comment]
that being said, releases should be pushed more frequently in order to prevent issues like this in the future.
