### ISSUE TITLE
Asking for .net to be installed when it already is installed 

### ISSUE THREAD

**Issue by Eberous** [Gamergotten/Infinite-runtime-tagviewer#116]
When trying to launch tagviewer, it'll ask for .net to be installed although it is.

It will continue to ask to be installed regardless of pc reset, install of all .net downloads etc

**Comment by Z-15** [comment]
Fix posted by ReecesPeeces#5827 on Discord. "I don't know if it will say this version cannot be installed due to a newer version already being installed or not, but if it does, try uninstalling any .net sdk install, and reinstall .net sdk 5" 

https://dotnet.microsoft.com/en-us/download/dotnet/5.0
