### ISSUE TITLE
Vehicle seat animations? 

### ISSUE THREAD

**Issue by stevieroth** [Gamergotten/Infinite-runtime-tagviewer#118]
im trying to use seats on the razorback only the marines can enter. Apparently the label text box is the actual animation so i changed it to an animation chief can use but he still wont get in the marine specific seat even with invalid for player turned off...any ideas? thanks! P.S it seems I can change the animations for seats such as the driver seat. 
![image](https://user-images.githubusercontent.com/119697210/205359338-96cecee5-841f-42c3-8ed2-088a666304f0.png)

**Comment by Z-15** [comment]
I have no idea unfortunately. I would suggest hopping on discord and joining some Halo related servers to ask this question. I leave a list of some good places below.

Infinite TV: https://discord.gg/TJGJvbtN (Halo Infinite Modding, not too active unfortunately.)
One Shot on my X: https://discord.gg/qJvFu8D4 (Used for custom games, but there are quite a few modders in there.)
Halo Mods: https://discord.gg/halomods (Mostly used for older Halo games, but someone might be able to help you.)
