### ISSUE TITLE
Infinite-runtime-tagviewer will not load due to missing .net files 

### ISSUE THREAD

**Issue by seekerA1** [Gamergotten/Infinite-runtime-tagviewer#119]
The infinite-runtime-tag viewer will not load due to missing .net files which will not download, I have tried so many different online solutions and thus far no luck with any of them, I really could use some expert advice/solution to this so I can continue to play Halo Infinite with mods. Thanks in advance.

**Comment by Gamergotten** [comment]
honestly i forgot the fact that other people had worked on this project, i think they changed it to .net 5.0 because they were too lazy to install 6.0 on their computer
my mistake

**Comment by MightyMackinac** [comment]
5.0 does work. Thanks!

**Comment by Z-15** [comment]
Issue resolved.
