### ISSUE TITLE
.net won't download when prompted and any version of .net refuses to work

### ISSUE THREAD

**Issue by aidansstuff** [Gamergotten/Infinite-runtime-tagviewer#120]
I have tried 5.0.100 + and 6 and 7

**Comment by itshyokin** [comment]
Had the same issue. This version of the **v5 .net** worked for me:
_https://download.visualstudio.microsoft.com/download/pr/1055020b-9c1a-4fd1-bb3e-64de0de2ee65/fbb705491eaea5fd9137de9fd230bbba/dotnet-sdk-5.0.405-win-x64.exe_

**Comment by Sopitive** [comment]
I believe IRTV was initially compiled with .NET 5. That would be the version to use if you are having trouble. Otherwise more details as to the error you are getting would help diagnose the issue further.

**Comment by Z-15** [comment]
I'll add the link to the version of .net itshyokin added to the readme and close the issue.
