### ISSUE TITLE
Spawning

### ISSUE THREAD

**Issue by NotUrDad1** [Gamergotten/Infinite-runtime-tagviewer#121]
When using crate projectile and spawning a vehicle, wont let you enter it. Instead Chief just kicks it around like a soccer ball. It gives you the option to enter it, but he wont actually enter it.

**Comment by Z-15** [comment]
Sorry for the late reply, are you still having this issue? Sounds similar to how the game acts when you spawn something in on a dedicated server, make sure you're playing offline first. I'll leave this open for now and wait for a reply, if I close it before you respond just create a new ticket.
