### ISSUE TITLE
"Offset failed, scanning... can't find HaloInfinite.exe"

### ISSUE THREAD

**Issue by panwiseman** [Gamergotten/Infinite-runtime-tagviewer#122]
Whenever I open IRTV and hit Load, all I get is an "offset failed" and "can't find .exe" messages. It was working fine a month ago, and I haven't updated/changed anything (maybe something broke with the latest Halo Infinite update?)

My "Set Game EXE..." location value is set right, but my "Set Pointer" is empty, as I don't know what to insert in there. 

Is there anything I can do? 

Thank you for the help :)

**Comment by panwiseman** [comment]
> 

BTW, I should add that I owe the game on Steam (which is where the program is reading the .exe file), and both are running on the same ssd.

**Comment by panwiseman** [comment]
> im probably not the best one to answer this, but i'll give it a shot and hopefully something here might help you or someone else
> 
> you might have to download the latest version, at least the latest version is working for me as of right now i haven't tested the autoupdater, so i couldn't tell you if that works, i'd recommend using the download button in the readme
> 
> as for if that doesn't work (although i dont believe these will solve the not finding exe problem):
> 
> 1. (this is very unlikely to be the issue, but its happened to me a couple of times,) make sure you're targeting the correct process, you can confirm this by going to the top left of the IRTV window, select "Options", then "Process Selector" and then just click the drop down that pops out to the right, then select the correct process
>    which realistically there should only ever be a single process in that dropdown, but if theres more, then have a play around with that until you find the correct process
> 2. try setting the pointer manually, you can do this by going to the top left of the IRTV window, click "Options" and then "Set Pointer...", this will create a new window that will allow you to write the new address
>    i think if you just copy paste this value in "HaloInfinite.exe+0x4362118", it'll have the correct address, press ok once you have pasted it
>    then i think you hit the load button and it should try loading the tags using that new address

Thank you -- updating to the latest version and putting the right pointer fixed it. I will close this issue now. 

Thanks again!

**Comment by Sh1n0suk3** [comment]
What is the pointer address for lastest Halo Infnite version?
