### ISSUE TITLE
Season 5 Bumps

### ISSUE THREAD

**Issue by ImpliedSkill** [Gamergotten/Infinite-runtime-tagviewer#129]
"TagBlocks exceeding 2 million entries" errors and dumping tag structs now requires a full reinstall due to it no longer allowing you to load Tags after.

**Comment by LaykaKiro** [comment]
I think this project was abandoned. That or the update is taking a bit...

**Comment by LaykaKiro** [comment]
Damn...

**Comment by ImpliedSkill** [comment]
As far as im aware its just the big man Z and hes busy. Ive been using this tool lately a LOT in conjunction with HIRT to find neat stuff about the guns and vehicles. I wish I knew how to fix it or maintain it. I would love to be able to.

**Comment by ImpliedSkill** [comment]
I've been using IRTV almost daily for like 4 months, I could better explain what I'm seeing and issues I've found in a VC if you want. I'm the definition of a script kiddie so trying to explain any issues through text is not ideal for me. Its why I was very vague with just saying the errors I've seen the most in the original post. My disc is impliedskill if you end up wanting to vc!

**Comment by ImpliedSkill** [comment]
No Issues anymore. This fixed it! Once again, Thanks for your time in looking into this for me <3

**Comment by Gamergotten** [comment]
marking as solved
if you have more issues with dumping structs, then feel free open a new issue request
