### ISSUE TITLE
IDs/addresses not showing up?

### ISSUE THREAD

**Issue by SquareMelon3** [Gamergotten/Infinite-runtime-tagviewer#135]
i came across a video from orca dork where he was able to modify his crosshair, i wanted to do the same but when i launch it and do exactly what it says in the video i cannot find half of the stuff that he has in the video that i wanted to use like the bloom diameter or just anything to do with the specific weapons crosshair, not only that but i also managed to come across something at the bottom of the specific weapons address saying "some tagblock exceeded 2million entries" and tried the previous solution to this issue that i saw someone help with (installing new plugin file) but came to no solution whatsoever. i tried both the windows and steam version and reinstalled different plugins folders and a larger tagnames.txt file along with following the most basic steps of troubleshooting like reinstalling irtv and restarting my computer yet nothing worked. Would this be because there has been an update to the game but not to this?

**Comment by Sopitive** [comment]
Best case I could tell is to clear your settings in your local appdata

**Comment by SquareMelon3** [comment]
after clearing my local settings and reinstalling another time, some more address(?) are showing up but there is still not the ones i am looking for, and it still seems like there is a lot less than what i have seen in orca dorks video.

**Comment by Connor-jt** [comment]
what do you mean by address?
if you meant as in tag files (items in the left side panel) then thats purely dependent on what map you're playing on

if you meant as in editable fields (right side panel) then there was either a major overhaul of the crosshair system within the past month (unlikely) or you're not using the correct tag structs
to fix that you simply need to dump the new tag structs (the option should be one of those dropdowns from the top of the window)

EDIT: if you're attempting to do this for campaign, then you will have to dump the campaign tag structs (IRTV no longer works on both campaign & multiplayer simultaneously, you'd have to change out the plugin files every time you swap between the two of them)

**Comment by SquareMelon3** [comment]
by addresses i meant the editable fields, my apologies. Anyways this seems to have fixed my problem, i appreciate your help kindly,
