### ISSUE TITLE
Some mapping out for .weapon tags

### ISSUE THREAD

**Issue by RevOcelotMGS** [Gamergotten/Infinite-runtime-tagviewer#22]
i343::Weapon::BarrelDefinition

1st float is Minimum Rounds per Minute
2nd float is Maximum Rounds per Minute
3rd float is Fire Recovery Time (how long it takes after a set of shots before the barrel can fire again)

That's the most data I can gather atm.

**Comment by Gamergotten** [comment]
awesome, i put those in

**Comment by cmumme** [comment]
@Gamergotten this has been done, u should close it
