### ISSUE TITLE
Mapping for .weapon magazine information

### ISSUE THREAD

**Issue by cmumme** [Gamergotten/Infinite-runtime-tagviewer#32]
# weapon_magazine_definition:
1. Unknown
2.  Starting ammo (clip+reserve)
3. Maximum clip ammo
4. Maximum reserve ammo
5. Unknown
6. Unknown
7. Unknown
8. How much ammo is transferred to the clip when you reload (no idea why they have this, confused me so much)

- Could be wrong on some, correct me if so.

**Comment by Gamergotten** [comment]
sick, imma chuck those in

**Comment by cmumme** [comment]
also, how do you put them in. i know it's in Halo/TagObjects/TagLayouts.cs, but what should i actually put in there if i want to add them myself

**Comment by cmumme** [comment]
i see this has been done, closing
