### ISSUE TITLE
Problem with release build v1.2

### ISSUE THREAD

**Issue by eyJake** [Gamergotten/Infinite-runtime-tagviewer#57]
Causing the game to crash on ( what I'd assume is an invalid) request, then few seconds later causing pc to involuntarily restart.

**Comment by Z-15** [comment]
Don't use the release build. V1.2 is currently 20 days old. There has been many updates sense then. Instead use the  "in development build" download link at the top of the Readme.

**Comment by eyJake** [comment]
> Don't use the release build. V1.2 is currently 20 days old. There has been many updates sense then. Instead use the "in development build" download link at the top of the Readme.

Yeah sorry, I was just pointing that issue out is all. Been using the in dev build since then.
