### ISSUE TITLE
"Byte" type not poking correctly.

### ISSUE THREAD

**Issue by PrototypeTV** [Gamergotten/Infinite-runtime-tagviewer#60]
When poking a "Byte" type, it does not poke correctly. Not sure how to properly explain it but here is a example: Input 21 into a "Byte" field, poke, and then reload that tag. It will now show the value as 33 instead of 21. It seems to be poking as a hexadecimal value instead of a decimal value if that makes sense. Sorry if I explained this poorly.

**Comment by Gamergotten** [comment]
i think this problem has been resolved, for some reason memory dll handles single bytes differently to 2 and 4 bytes
 lemme know how it turns out

**Comment by PrototypeTV** [comment]
It seems to be working fine now. Thank you.
