### ISSUE TITLE
hlmt model crashes IRTV on scroll through variants

### ISSUE THREAD

**Issue by Bonepunk** [Gamergotten/Infinite-runtime-tagviewer#69]
When I try to scoll through variants in hlmt models like the pelican, ghoste or master chief it crashes IRTV.
I use the latest In-development build.

**Comment by Gamergotten** [comment]
i looked into this last night before going to sleep, it appears a previously mapped out value has a longer byte length than it should have
i can implement a temporary fix until i do it properly, which'll probably encourage me to just not do it the proper way

**Comment by Gamergotten** [comment]
ok fix has been pushed for both issues

**Comment by Gamergotten** [comment]
actually imma unclose this issue until i do a proper fix - which is mapping out that value properly

**Comment by Gamergotten** [comment]
ok i can now close this issue
