### ISSUE TITLE
Copying a Pointer to a different Tag's block of the same type crashes the game when referenced

### ISSUE THREAD

**Issue by anOrcaDork** [Gamergotten/Infinite-runtime-tagviewer#71]
When poke/loaded it completely nulls all of it's values in the block instead of leaving them normal or overwriting them with the referenced address's values. PRetty sure putting 0's where there's definitely not supposed to be is gonna crash the game.
![image](https://user-images.githubusercontent.com/97447006/148763881-dd8d2f4b-cb92-49a6-b620-968bca9e7cef.png)
 Here's me referencing the mlrs target tracking block, onto the banshee bomb. The banshee bomb has its own default values for tracking type, not 0x0 lol

**Comment by Gamergotten** [comment]
what

**Comment by Gamergotten** [comment]
ok apparently this is resolved
