### ISSUE TITLE
Game crashes when spawning ai in Microsoft Store version of halo

### ISSUE THREAD

**Issue by CMike916** [Gamergotten/Infinite-runtime-tagviewer#82]
Found a video online about this and decided to give it a try and when I try to spawn an ai my game crashes.

**Comment by Baxuvis** [comment]
It's edited in the GLPA tag, There's a really finnicky method to do it which involves loading the tags on the main menu, opening the GLPA, switch to the second variant of the top block, put the marine biped into the biped block, but don't poke. Hit load on the campaign, and as soon as the bar hits 100% and the background changes, hit poke. When you eventually load in, if your camera is floating in the middle of the map, then you know you did it right. Hit load tags on IRTV again, reopen .glpa, switch to the second variant, swap the marine biped for the biped of your choice. When you hit poke, your camera should teleport back to you and you will be the biped you selected

**Comment by Baxuvis** [comment]
Ai is spawned using effect tags

**Comment by CMike916** [comment]
I tried it again and I can spawn a grunt but when I try to spawn a marine the game instantly crashes. Do I have to progress through the campaign?

**Comment by Baxuvis** [comment]
> I tried it again and I can spawn a grunt but when I try to spawn a marine the game instantly crashes. Do I have to progress through the campaign? This is the tutorial I followed : https://www.youtube.com/watch?v=0SKtKL-4Fpc


You can only spawn in regular Character tags.  If it says AI or anything funky in the name. It's going to crash.   The game isn't designed to be modded.  Expect the game to crash when you make changes the game doesn't like.   This is not an IRTV issue..   you can find support for modding in the halomods discord / reddit.  

Good luck out there !

-baxuvis

**Comment by Gamergotten** [comment]
an unloaded tag should not cause issues when attempting creation, however creating a tag that is not supposed to be created will most definitely cause issues

you said a grunt works but the marines do not, this may be because you are attempting to create ai style/stimulus versions of that character

however if you're trying to create the normal marine, than that is interesting that you're running into an issue with that

so long as a tag is loaded then it should work, the next patch to the program will hopefully allow people to understand the problem with unloaded tags

**Comment by CMike916** [comment]
I see, thank you guys for the responses.

**Comment by PaulsgamingLive** [comment]
what version of the game are you using? I can't get any AI to spawn anymore

**Comment by Baxuvis** [comment]
Could you Elaborate? Explain what you're doing step by step so we can try to figure out what's going wrong

**Comment by PaulsgamingLive** [comment]
My mistake sorry, I had effects turned to low -_-
