### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by MiisterNiice** [Gamergotten/Infinite-runtime-tagviewer#93]
Good afternoon,

Sorry to bother you guys with this, but I am new to the modding scene. I thought I would unzip the infinite runtime tag viewer and see an EXE to click. This is not the case. Is there a guide on how to use this set of files to mod infinite? Thank you do much in advance. I am on PC and am running it through the Xbox app.

**Comment by Baxuvis** [comment]
![Screenshot_20220204-024230_Chrome](https://user-images.githubusercontent.com/36710974/152498421-e5546562-e448-40f4-b6c1-47846cf4a1f1.jpg)

Please read the Readme section at the homepage of the github repo.

You will find a download link there.

**Comment by Baxuvis** [comment]
The code stored on github is the source code.

The .NET system on github compiles it for you I to a zip by clicking that button.
